apiVersion: v1
kind: Service
metadata:
  name: apm
  namespace: elasticsearch
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet1"
  labels:
    component: elasticsearch
    role: apm
spec:
  selector:
    component: elasticsearch
    role: apm
  ports:
  - name: http
    port: 80
    targetPort: 8200
    protocol: TCP
  type: LoadBalancer