apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-snapshots
  namespace: elasticsearch
spec:
  schedule: "0 */2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-snapshots
            image: akhilrajmailbox/elasticsearch:cron-snapshots
            # args:
            # - /bin/bash
            # - -c
            # - python3 snapshot.py
            env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: "myenv"
              value: "production"

            - name: "host"
              value: "http://192.168.0.12:9200/"

            - name: "indicesdeldays"
              value: "90"

            - name: "snaprepo"
              value: "development-elasticsearch-storage"

            - name: "snapdeldays"
              value: "365"

            volumeMounts:
            - name: "snapshot"
              mountPath: "/opt/snapshot.py"
              subPath: "snapshot.py"
          volumes:
            - name: "snapshot"
              configMap:
                name: "snapshot-cm"
          restartPolicy: OnFailure                
