apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet1"
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
  type: LoadBalancer
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: elasticsearch
#   namespace: elasticsearch
#   labels:
#     component: elasticsearch
#     role: client
# spec:
#   ports:
#   - name: http
#     port: 9200
#   selector:
#     component: elasticsearch
#     role: client
#   type: NodePort # Or LoadBalancer in production w/ proper security